-- SIMULAÇÃO DE RESTORE COM VARIOS DATAFILE EM ARQUIVO DE BKP. 

--Criando Banco de dados
 
USE MASTER
CREATE DATABASE AULA_BK
 ON  PRIMARY 
( 
  NAME = N'AULA_BK1', FILENAME = N'C:\TEMP\AULA_BK1.mdf' , 
  SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB 
  ),
 filegroup AULA
  (
  NAME = N'AULA_BK2', FILENAME = N'C:\TEMP\AULA_BK2.ndf' , 
  SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB 
  )  
 LOG ON 
( NAME = N'AULA_BK_log', FILENAME = N'C:\TEMP\AULA_BK_log.ldf' , 
  SIZE = 1072KB , MAXSIZE = 2048MB , FILEGROWTH = 10%)



USE AULA_BK
CREATE TABLE REGISTROS (
	ID_REGISTRO INT IDENTITY(1,1)PRIMARY KEY,
	CARGA VARCHAR (50),	
) 
GO

 
--Populando Tabela COM 1000 REGISTRO
INSERT INTO REGISTROS VALUES ('1 CARGA')
GO 1000



 -- BACKUP FULL  
BACKUP DATABASE AULA_BK
TO DISK = 'C:\TEMP\AULA_BK-FULL.bak'
WITH INIT, COMPRESSION, CHECKSUM, STATS = 10,NAME = 'C:\TEMP\AULA_BK-FULL.bak'


 
--Populando Tabela COM 1000 REGISTRO
INSERT INTO REGISTROS VALUES ('2 CARGA')
GO 1000




 -- BACKUP DIFF  
BACKUP DATABASE AULA_BK
TO DISK = 'C:\TEMP\AULA_BK-DIFF.bak'
WITH DIFFERENTIAL,   COMPRESSION, CHECKSUM, STATS = 10,NAME = 'C:\TEMP\AULA_BK-DIFF.bak'




--Passo 5
--Populando Tabela COM 1000 REGISTRO
INSERT INTO REGISTROS VALUES ('3 CARGA')
GO 1000


 
 -- BACKUP LOG 
BACKUP LOG AULA_BK
TO DISK =   'C:\TEMP\AULA_BK-LOG1.bak'
WITH  NAME = 'C:\TEMP\AULA_BK-LOG1.bak'


 --Verificando
USE AULA_BK2
SELECT COUNT(*),CARGA CARGA FROM REGISTROS
GROUP BY CARGA


--USE MASTER
--ADICIONANDO ARQUIVO DE DADOS
ALTER DATABASE AULA_BK
ADD FILE
(
NAME ='AULA_BK4',                              
FILENAME = N'C:\TEMP\AULA_BK4.ndf' ,
   SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB 
) TO FILEGROUP AULA
 
 

--Passo 8
--Inserindo mais registros
INSERT INTO REGISTROS VALUES ('4 CARGA')
GO 1000
 

-- BACKUP DE LOG CONTENDO O NOVO ARQUIVO .NDF
BACKUP LOG AULA_BK
TO DISK =   'C:\TEMP\AULA_BK-LOG-2.bak'
WITH  NAME = 'C:\TEMP\AULA_BK-LOG-2.bak'



/* :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::  */ 
--RESTORE DE UMA NOVA BASE DE DADOS 
/* :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::  */ 
USE MASTER
GO
DROP DATABASE AULA_BK


 
 
 -- FULL
RESTORE DATABASE AULA_BK_2
FROM DISK = 'c:\TEMP\AULA_BK-FULL.bak'
WITH NORECOVERY,STATS = 5 , 
 MOVE N'AULA_BK1'    TO N'C:\TEMP\AULA_BK1_v2.mdf', 
 MOVE N'AULA_BK2'    TO N'C:\TEMP\AULA_BK2_v2.ndf',
 MOVE N'AULA_BK_log' TO N'C:\TEMP\AULA_BK_log_v2.ldf' 
 

  
 -- DIFF
RESTORE DATABASE AULA_BK_2 
FROM DISK='C:\TEMP\AULA_BK-DIFF.bak' 
WITH  NORECOVERY  
 
 
RESTORE FILELISTONLY  FROM DISK = 'C:\TEMP\AULA_BK-LOG1.bak' 

-- LOG 1 
RESTORE DATABASE AULA_BK_2 
FROM DISK='C:\TEMP\AULA_BK-LOG1.bak' 
WITH  NORECOVERY  




-- LOG 2 CONTENDO O NOVO ARQUIVO .NDF ( FALHA AO RESTAURAR  ) 
RESTORE DATABASE AULA_BK_2 
FROM DISK='C:\TEMP\AULA_BK-LOG-2.bak' 
WITH   RECOVERY  , REPLACE 




-- VERIFICAR QUAIS DATAFILES EXISTEM NO BACKUP.  
RESTORE FILELISTONLY  FROM DISK = 'C:\TEMP\AULA_BK-LOG-2.bak' 


-- LOG 2 CONTENDO O NOVO ARQUIVO .NDF ( INFORMANDO A CRIAÇÃO DE UM NOVO ARQUIVO PARA O DATAFILE AULA_BK4 ) 
RESTORE DATABASE AULA_BK_2 
FROM DISK='C:\TEMP\AULA_BK-LOG-2.bak' 
WITH   RECOVERY ,  MOVE N'AULA_BK4'    TO N'C:\TEMP\AULA_BK4_v2.Ndf'  


 
